theme: minima
title: Min tittel i config.yml
author: GitHub User
email: evelin.grana@outlook.no
description: > # this means to ignore newlines until "baseurl:"
  En test-blogg - ikke noe mer. Oppdateres i config.yml

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  evelingrana # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
